### ISSUE TITLE
Pretrained model release

### ISSUE THREAD

**Issue by muhammad-ahmed-ghani** [weepiess/StyleFlow-Content-Fixed-I2I#1]
Hi @weepiess when will you release the pretrained models and infrerence code ?

**Comment by weepiess** [comment]
> Hi @weepiess when will you release the pretrained models and infrerence code ?

The pre-trained models and the inference code would be released in two weeks :)

**Comment by tg-bomze** [comment]
Hello @weepiess. Do you plan to publish a pre-trained model? The results are impressive :)

**Comment by weepiess** [comment]
@tg-bomze @muhammad-ahmed-ghani Hi, sorry for the delay. The pre-trained model for COCO->Wikiart has been updated. Others would be coming soon :)
