### ISSUE TITLE
can you release pretrained model for summer to winter

### ISSUE THREAD

**Issue by aarjunsrinivasan** [weepiess/StyleFlow-Content-Fixed-I2I#10]

**Comment by WeichenFan** [comment]
Hi,

Sorry for the late response.

Thank you for your interest. Currently, we are working on a new model and may not have time for releasing ***summer2winter*** model. 

You can directly use the COCO2Wikiart setting and try different $k$ values (0.6 might be good enough). If you have any problem with that feel free to contact me. :)
