### ISSUE TITLE
input size change

### ISSUE THREAD

**Issue by Daehyun41** [weepiess/StyleFlow-Content-Fixed-I2I#11]
Hello.
Thank you for your code.

I have some questions for input size change for test.
I want to use input content images that are many different size.

How can I change code?

def get_data_loader_folder_pair(input_folderA, input_folderB, info_txt, batch_size, train, keep_percent, new_size=None,
                           height=256, width=256, num_workers=8, crop=True,get_direct=True,used_domain=None,train_vr=False,return_paths=False):
    if train_vr is False:
        transform_list = []
        # transform_list.append(transforms.RandomResizedCrop((436,356),scale=(0.7,1.0)))
        transform_list.append(transforms.Resize((436,356)))
        transform_list.append(transforms.ToTensor())
        transform = transforms.Compose(transform_list)
        transform2=None
    else:
        transform_list = []
        transform_list.append(torchvision.transforms.Lambda(lambda img: crop_vr_img(img)))
        transform_list.append(transforms.Resize((436,356)))
        transform_list.append(transforms.ToTensor())
        transform = transforms.Compose(transform_list)

        transform_list2 = []
        transform_list2.append(torchvision.transforms.Lambda(lambda img: crop_real_img(img)))
        transform_list2.append(transforms.Resize((436,356)))
        transform_list2.append(transforms.ToTensor())
        transform2 = transforms.Compose(transform_list2)

**Comment by WeichenFan** [comment]
HI,

Sorry for the late response. If you want to not freeze the image size during the inference, you could simply modify the code to:
~~~ Python
        transform_list = []
        #transform_list.append(torchvision.transforms.Lambda(lambda img: crop_real_img(img)))
        #transform_list.append(transforms.Resize((300,400)))
        transform_list.append(transforms.ToTensor())
        transform = transforms.Compose(transform_list)
~~~
, which refers to not resizing the image during the test phase. (***And remember to use batch size with 1***)
