### ISSUE TITLE
about video 2 anime in this project ?

### ISSUE THREAD

**Issue by zhanghongyong123456** [weepiess/StyleFlow-Content-Fixed-I2I#13]
Can we achieve such an effect in this project? The animation effect output is on the left, and the source video input is on the right.
![image](https://github.com/weepiess/StyleFlow-Content-Fixed-I2I/assets/48466610/171595b6-65aa-4779-ac07-2d6d8792b751)

**Comment by WeichenFan** [comment]
Yes, you could transform from the source to the target first, and then concat the generated images with the source images.

**Comment by arrrrr3186** [comment]
Hi @zhanghongyong123456,  @WeichenFan
can we do image-to-video transformation?
