### ISSUE TITLE
rootA: /path/to/train_src.txt

### ISSUE THREAD

**Issue by xyiiinexg3** [weepiess/StyleFlow-Content-Fixed-I2I#3]
![image](https://user-images.githubusercontent.com/65646825/190966905-ce58d9f8-7c99-4097-bb90-81dd7c353921.png)

请问，rootA: /path/to/train_src.txt是什么意思？然后#example /path/COCO_train2014_000000188902.jpg又是什么意思？我不是很能理解这个路径。

excuse me, could you tell me the meaning of the rootA/rootB, and the example? Why rootA: .txt? Thank you!

**Comment by WeichenFan** [comment]
> ![image](https://user-images.githubusercontent.com/65646825/190966905-ce58d9f8-7c99-4097-bb90-81dd7c353921.png)
> 
> 请问，rootA: /path/to/train_src.txt是什么意思？然后#example /path/COCO_train2014_000000188902.jpg又是什么意思？我不是很能理解这个路径。
> 
> excuse me, could you tell me the meaning of the rootA/rootB, and the example? Why rootA: .txt? Thank you!

Hi,

rootA 的路径指代存放了source img路径的txt文件，rooB 的路径指代存放了target img路径的txt 文件。
例如:
~~~
rootA: /home/xxx/trainA.txt
rootB: /home/xxx/trainB.txt
~~~

rootA里存放着source img的绝对路径
~~~
/Your Path/COCO/train2014/COCO_train2014_000000144796.jpg
/Your Path/COCO/train2014/COCO_train2014_000000338143.jpg
/Your Path/COCO/train2014/COCO_train2014_000000136698.jpg
...
~~~
* /Your Path/ 代表你的路径

rooB 同理.

Rgds

**Comment by xyiiinexg3** [comment]
谢谢！！
