### ISSUE TITLE
Proof of content-fixed

### ISSUE THREAD

**Issue by xyiiinexg3** [weepiess/StyleFlow-Content-Fixed-I2I#4]
![image](https://user-images.githubusercontent.com/65646825/193747280-7a6fb9f0-a790-4719-8159-e44e6726dcc3.png)

公式（14）的第一个等号成立的话，根据内容特征的定义，说明CGA（fx, fs）的均值=fx^的均值，也就是说fx^=CGA(fx, fs)，是这样的意思吗？但这个等号是从哪里推导出来的呢？

![Uploading image.png…]()

且公式（12）表明，fx^=SAN(fx, fs)。不是很懂他们之间的关系了。

**Comment by WeichenFan** [comment]
Hi xyiiinexg3,

Thank you for your interest.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/112800544/194681415-64be9b6f-5552-4101-826f-b6584e802eff.png">
 
Rgds

**Comment by xyiiinexg3** [comment]
非常谢谢您的回复，收到邮件但忘记回复了T^T.......
后续看了AdaIN和ArtFlow，就对整个思路就都很清晰了。
最后，您的想法很棒！
