### ISSUE TITLE
Conflicts between required modules

### ISSUE THREAD

**Issue by albusdemens** [weepiess/StyleFlow-Content-Fixed-I2I#8]
Hello, first of all congratulations on the impressive work! I would like to try your model in inference mode but I have some issues installing the required packages. Could you share your yaml file? 

The command `pip install --force-reinstall -v "pytorch==1.5.0"` gives me the error `Link requires a different Python (3.6.0 not in: '>=3.7')`.

**Comment by weepiess** [comment]
> Hello, first of all congratulations on the impressive work! I would like to try your model in inference mode but I have some issues installing the required packages. Could you share your yaml file?
> 
> The command `pip install --force-reinstall -v "pytorch==1.5.0"` gives me the error `Link requires a different Python (3.6.0 not in: '>=3.7')`.

Hi, thank you for your interest.

You can just use Python 3.7. Let me know if you meet any problems running the codes.

**Comment by albusdemens** [comment]
Thanks for the hint! I'm running Ubuntu 20.04.4 LTS and to avoid conflicts
I had to install Python 3.7.2. Everything worked fine after that.
